fibo : Fibonacci.cc
	g++ Fibonacci.cc -o fibo

square : magic_square.cc
	g++ magic_square.cc -o square

sort : sort_int.cc
	g++ sort_int.cc -o sort

clean :
	rm fibo square sort

all :
	make fibo
	make square
	make sort
